### ISSUE TITLE
[ts] Cannot find module './Index.module.scss'. (fresh install)

### ISSUE THREAD

**Issue by altruisticsoftware** [tdharmon/gatsby-starter-typescript-sass#1]
Ran `gatsby new gatsby-site https://github.com/tdharmon/gatsby-starter-typescript-sass` and vscode gets upset

![image](https://user-images.githubusercontent.com/12105346/47864387-75d62900-ddc7-11e8-8e4d-9dca6d7c6031.png)

**Comment by tdharmon** [comment]
> @altruisticsoftware I did a lot of research into this and determined that the best fix was to add a 'catch-all' type definition for `.scss` files. I'm updating the repo to include these changes. If you need to make these changes in your own project:

1. Create a tsconfig file and make sure you set the `jsx` compiler option to `react`
2. Create a global `d.ts` file and add a catch all definition. You can see an example of one [here](https://github.com/zeit/next-plugins/issues/91#issuecomment-372089878).

**Comment by LouBerry** [comment]
@thetrevorharmon Hi even with css modules and  ` "gatsby": "^2.24.81"` the error happens.
The workaround works quite well for me. But is it still necessery or am I doing something wrong.
My app is based on the gatsby [hello wolrd]( https://github.com/gatsbyjs/gatsby-starter-hello-world)

**Comment by thetrevorharmon** [comment]
@LouBerry this workaround is necessary because typescript doesn't have a way of knowing what the shape of your css looks like (so it can't know what the `styles` object looks like). It is necessary unless you have a way of generating types based off the CSS (which is still pretty hard to do AFAIK).

**Comment by LouBerry** [comment]
Thanks for taking the time and clarifying for me

**Comment by martin-braun** [comment]
Hey @thetrevorharmon. Thank you for your support on this issue. I think it would be the right move to include such a declaration file in the starter. But honestly, I would prefer to get suggestions for my classNames, so there should be explicit typing as the SCSS files get edited. 

Microsoft's SPFX technology for SharePoint proves that this is possible. They kinda came up with their own solution, but it might be useful to investigate. The compiler does pre-execute a process that will create / update `.module.scss.ts` files next to the `module.scss` files that will be imported by the user.

I loved the strong typing of class names when I worked in that environment and I would enjoy it being part of Gatsby. I think this should be part of [`gatsby-plugin-sass`](https://www.gatsbyjs.com/plugins/gatsby-plugin-sass/) and not `gatsby-starter-typescript-sass`, so it will be available for all starters that use this plugin.
